spring.application.name=v2i-notification
server.port=8003

# Upload
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Database
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:v2i}}
spring.datasource.username=${POSTGRES_USER:root}
spring.datasource.password=${POSTGRES_PASSWORD:root}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Queue
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=${RABBITMQ_USER:root}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:root}

#Actuator
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
management.health.db.enabled=true

# Mail
spring.mail.host=${MAIL_HOST:sandbox.smtp.mailtrap.io}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:fe752669be8f43}
spring.mail.password=${MAIL_PASSWORD:1adcf21f230bb6}
spring.mail.properties.mail.smtp.auth=true
notification.mail.from=${MAIL_FROM:${spring.mail.username}}

